### ISSUE TITLE
License Details

### ISSUE THREAD

**Issue by jafeerh** [jbryer/DataCache#5]
Cannot find the licensing details? Please point me to the licensing URL

**Comment by jbryer** [comment]
Per the DESCRIPTION file, it is licensed under GPL: https://github.com/jbryer/DataCache/blob/master/DESCRIPTION
https://www.gnu.org/licenses/gpl-3.0.html

**Comment by jafeerh** [comment]
Thank you very much. 

The GPL version was not mentioned in the description file. 

Usually, there is a license file I see associated with packages, which I couldn't find.  That's why opened the thread.

Thanks again.
